# ["def run_program(Running_Map):",
# "    pc = 0",
# "    while True:",
# "        if hero.findNearestEnemy():",
# "        hero.attack(hero.findNearestEnemy())",
# "        hero.say('soldier')",
# "    else:",
# "        command = Running_Map[pc]",
# "        if 'd' in command:",
# "            if command['d'] == 0:",
# "                hero.moveUp(command['s'])",
# "            if command['d'] == 1:",
# "                hero.moveRight(command['s'])",
# "            if command['d'] == 2:",
# "                hero.moveDown(command['s'])",
# "            if command['d'] == 3:",
# "                hero.moveLeft(command['s'])",
# "        elif 'd' in command:",
# "            hero.say(command['s'])",
# "        elif 'd' in command:",
# "            if command['a'] == '':",
# "                if hero.findNearestEnemy():",
# "                    hero.attack(hero.findNearestEnemy())",
# "            else:",
# "                hero.attack(command['a'])",
# "        pc += 1"]
import src.hero
hero = src.hero.hero_model()
#Nothing here